version: "3.9"
services: 
  mongo:  
    image: mongo
    restart: always
    ports:
      - "27017:27017"
   
  api:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
   
  